"""Create Game Model

Revision ID: 0187b7d46e5b
Revises: 602f8990f5e7
Create Date: 2023-12-13 10:59:57.103708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0187b7d46e5b'
down_revision = '602f8990f5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
